version: "3"

services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
    ports:
      - "8000:8000"
      - "5173:5173"
    networks:
      - minha-regiao
    depends_on:
      - postgis
  postgis:
    image: postgis/postgis:17-3.5
    container_name: postgis
    ports:
      - "9002:5432"
    networks:
      - minha-regiao
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgis_data:/var/lib/postgresql/data
    
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  minha-regiao:
    driver: bridge

volumes:
  postgis_data:
    driver: local