version: "3"

services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
    ports:
      - "8000:8000"
      - "5173:5173"
    networks:
      - minha-regiao
  db:
    image: postgis/postgis:17-3.5
    ports:
      - "9002:5432"
    networks:
      - minha-regiao
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
networks:
  minha-regiao:
    driver: bridge
