version: "3"

services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
    ports:
      - "8000:8000"
      - "5173:5173"
    networks:
      - minha-regiao
networks:
  minha-regiao:
    driver: bridge
